services:
  # 1. Backend Laravel (API)
  laravel-backend:
    build:
      context: ./server-laravel
      dockerfile: Dockerfile
    container_name: laravel-prod
    restart: always
    ports:
      - "80:80" # Tu API de Laravel estará disponible en el puerto HTTP por defecto (80)
    env_file:
      - ./server-laravel/.env # Carga las variables desde el .env de Laravel
    deploy:
      resources:
        limits:
          memory: 1G

  # 2. Sistema GLPI
  glpi:
    image: glpi/glpi:latest
    container_name: glpi-prod
    restart: always
    ports:
      - "8080:80" # GLPI estará disponible añadiendo :8080 a la IP de tu EC2
    environment:
      # Apuntamos GLPI directamente a la instancia de AWS RDS
      - GLPI_DB_HOST=tu-instancia-rds.us-east-1.rds.amazonaws.com
      - GLPI_DB_NAME=glpi_db
      - GLPI_DB_USER=admin_rds
      - GLPI_DB_PASSWORD=tu_password_seguro
    volumes:
      # Persistencia vital para que GLPI no pierda documentos o plugins si el contenedor se reinicia
      - ./server-glpi/glpi_data:/var/www/html/glpi
    deploy:
      resources:
        limits:
          memory: 1G