services:
  # 1. Base de Datos Local
  db:
    image: mariadb:10.11
    container_name: db-local
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root_pass
      - MARIADB_USER=user_local
      - MARIADB_PASSWORD=pass_local
      # Eliminamos MARIADB_DATABASE para que el script cree las dos.
    volumes:
      - ./mysql_data:/var/lib/mysql
      # Este volumen inyecta el script para crear ambas bases de datos:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      # CAMBIO DE PUERTO: Tu PC usará el 3307 (XAMPP es feliz), el contenedor usa el 3306.
      - "3307:3306"

  # 2. Backend Laravel
  laravel-backend:
    build:
      context: ./server-laravel
      dockerfile: Dockerfile
    container_name: laravel-local
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./server-laravel:/var/www/html
    env_file:
      - ./server-laravel/.env
    environment:
      # Laravel sigue apuntando al puerto 3306 interno de la red de Docker
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_biblioteca # Base de datos específica para Laravel
      - DB_USERNAME=user_local
      - DB_PASSWORD=pass_local

  # 3. Sistema GLPI
  glpi:
    image: glpi/glpi:latest
    container_name: glpi-local
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      # GLPI apunta a su propia base de datos
      - GLPI_DB_HOST=db
      - GLPI_DB_NAME=glpi_db # Base de datos específica para GLPI
      - GLPI_DB_USER=user_local
      - GLPI_DB_PASSWORD=pass_local
    volumes:
      - ./server-glpi/glpi_data:/var/www/html/glpi

  # 4. Mailpit
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-local
    restart: always
    ports:
      - "8025:8025" 
      - "1025:1025"